### ISSUE TITLE
Question about LoD Selection

### ISSUE THREAD

**Issue by pengfei666** [Esri/i3s-spec#10]
Hi, Guys
    I have a question about "LoD Selection". When we are working on loading a slpk, we find all the nodes' index document say maxError: 0. So I want to know how to deal with maxError: 0. And is the data legal?

Thank you.

**Comment by sreinhard** [comment]
For the `maxScreenThreshold` error metric, `maxError` means that you should replace the node with it's children as soon as the nodes bounding sphere has a screen radius larger than `maxError` pixels. In this sense a value of `0` means you should always load it's children, or if it's a leaf node, you should always display it.

**Comment by pengfei666** [comment]
Thank you. It would be good if you could update the spec document.

**Comment by Shtirlic81** [comment]
Hello,

I have a question regarding this issue.

When do I switch the LoD is the maxError is 523.21?

**Comment by sreinhard** [comment]
@Shtirlic81 The LoD computation works as follows

1. Project bounding sphere on screen plane and compute its radius in pixels. (see eg. here for an example of how to do this: https://stackoverflow.com/questions/21648630/radius-of-projected-sphere-in-screen-space)
2. Switch LoD to children if this radius is bigger than maxError.
