### ISSUE TITLE
i3s convert tool does work when slpk file's name contains Chinese characters!

### ISSUE THREAD

**Issue by beginor** [Esri/i3s-spec#106]
The name of the slpk file is `439唐家` ， try to update it with i3s convert tools, the output is:

```bat
i3s_converter.exe -u 439唐家
Input file "439鍞愬.slpk" does not exist
```

But I changed the name from `439唐家` to `439` ， it works.

**Comment by congying2** [comment]
南京汉图 有一套稳定转换方案，具体可联系 http://www.handsmap.cn/

**Comment by rvargasESRI** [comment]
@beginor Sorry for the delay, but this issue should now be resolved.
