### ISSUE TITLE
Gaps between tiles after upgrade slpk files to 1.7 with i3s convert tool

### ISSUE THREAD

**Issue by beginor** [Esri/i3s-spec#107]
The version of my slpk file is 1.5, after update it to 1.7 with i3s convert tool, there are many gaps between tiles.

this is the screenshot of version 1.5

![image](https://user-images.githubusercontent.com/159065/98315137-80f56c80-2012-11eb-8b13-3c338c3f97f3.png)

this is the screenshot of version 1.7

![image](https://user-images.githubusercontent.com/159065/98315160-8e125b80-2012-11eb-9e0f-1fd469c4bc06.png)

**Comment by rvargasESRI** [comment]
Hello @beginor 
Thanks for bringing this to our attention.  It is now fixed in the master branch.
