### ISSUE TITLE
Question about class Image

### ISSUE THREAD

**Issue by pengfei666** [Esri/i3s-spec#11]
Hi Folks,
   I have a question about this Part https://github.com/Esri/i3s-spec/blob/a22e94d8bcf484f106f0231baa01793a58959741/format/Indexed%203d%20Scene%20Layer%20Format%20Specification.md#class-image.

As we know, the texture images often are compressed. So here we give a byteOffset and Length fields, the numbers should before compressed or after?

**Comment by pengfei666** [comment]
Assume we have several images, we put them into one binary file. How we put them? 
Compress images separately then combine them into a single binary file, or 
combine them into a single binary file first, then compress the whole file?

**Comment by thorsten-reitz** [comment]
The original intent was to compress images individually. I don't think there is much to be gained to compress them again. Maybe one of the current maintainers can comment?

**Comment by sreinhard** [comment]
Hey Pengfei,
Combining multiple images into a single binary file is not supported by all clients, so we recommend against using this feature of the i3s spec. Also textures are usually large resources so there is not much to gain from combining them. If you have many small textures, you should consider combining them into a texture atlas.

To answer your question, the offset and length fields are before gzip compression. So for uncompressed image data (eg. S3TC textures), you would combine them in a binary file and then compress them. For compressed formats, like JPEG or PNG, as @thorsten-reitz said you would not use gzip compression at all , so you would just combine the images.

**Comment by pengfei666** [comment]
@sreinhard  Thank you very much.  As you say
> the offset and length fields are before gzip compression.
I think the length should be uncompressed size even if we only have one dds image. Isn't it?

**Comment by pengfei666** [comment]
For showing the question clearly, I paste a screenshot of one data.
![l r1j6 ffgmt3rtfxanc3](https://user-images.githubusercontent.com/25144819/39283864-ee673018-4942-11e8-91c1-2027d9822f58.png)
