### ISSUE TITLE
Setting threading doesn't work

### ISSUE THREAD

**Issue by jrounsley** [Esri/i3s-spec#124]
Hi there

It appears as though the tool does not actually use the thread count subcommand. Regardless of the number set, only 1 core is used. Is this user error, or an issue with the converter?

Thanks
Jess

**Comment by rvargasESRI** [comment]
@jrounsley thanks for bringing this to our attention.
This has been addressed in https://github.com/Esri/i3s-spec/pull/125 
Closing issue
