### ISSUE TITLE
Support for Basis Universal Texture format In ArcGIS Enterprise

### ISSUE THREAD

**Issue by zssai** [Esri/i3s-spec#127]
On which version of ArcGIS Enterprise will the Basis Universal Texture formate  be supported ?
Will the ArcGIS Enterprise 10.8.1 support the texture format by applying patches ?

**Comment by rvargasESRI** [comment]
@zssai 
Scene viewer on enterprise in 10.9 is the earliest released cycle but I have heard of no plans to patch 10.8.1 for basis support.
