### ISSUE TITLE
Azure / AWS in WebApp

### ISSUE THREAD

**Issue by bloigge** [Esri/i3s-spec#133]
The i3s_converter supports the export to azure and aws. Is there any tutorial how to consume slpk / i3s hosted on azure / aws in a web application using the esri javascript sdk?

**Comment by bloigge** [comment]
I am actually looking for a way how to consume i3s stored on Azure via the JS API. So I guess the new docs will fit. Thank you for the update!

**Comment by bloigge** [comment]
Can we directly consume the data from a Blobstorage via the JS API or do we need to do the hosting using ArcGIS Enterprise?

**Comment by rvargasESRI** [comment]
@bloigge 
The workflow would be to have the blobstorage registered on a data store on ArcGIS server, and to create a service from that data store, then consume that service using JS API.

**Comment by rvargasESRI** [comment]
@bloigge 
https://pro.arcgis.com/en/pro-app/latest/help/data/services/use-web-scene-layers.htm

Here a way to automate a part of your desired workflow using Python and the ArcGIS API.

Hope this helps!
