### ISSUE TITLE
i3s_converter -v failed every time without any message

### ISSUE THREAD

**Issue by disednet** [Esri/i3s-spec#135]
I generated a "slpk" file and then started verification of the resulting model. At the first time, I decided to use only i3s_converter -v "model.slpk" for checking, and this tool allowed me to find some errors but after several changes in the model (slpk) the tool started failing every time I ran the checking process without any messages. The log file wasn't created at all.

**Comment by disednet** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/12100376/145779241-ecc75f71-ddf3-491d-8c91-7fa52ac9ddcd.png)

**Comment by disednet** [comment]
I attached the  [problem file located on google drive](https://drive.google.com/file/d/133KWrEsMUx-yMgiCEEVGMPgkAvM3RFTz/view?usp=sharing ). Today I tried to upload it into ArcGIS and the program failed without error messages. I thought if the file contained a problem the program would note it.

**Comment by rvargasESRI** [comment]
@disednet We will take a look into this, thank you for bringing it to our attention

**Comment by disednet** [comment]
If I understand it correctly you use gzip for statistic info in the main layer and this archive should be obtained with the special flag "FLG.FNAME". If an archive doesn't contain this flag it will lead to the crashing of the application. It seems very strange because other archives in slpk don't contain the flag.
