### ISSUE TITLE
[i3s_converter.exe] Does extract (-e) slpk to eslpk to cloud storage also support multithreads? 

### ISSUE THREAD

**Issue by JackFanZhang** [Esri/i3s-spec#136]
Hello, could someone please confirm if MultiThreads is also supported when extract (-e) slpk to eslpk to cloud storage, or it is only for the convert (-c) function? 

I have tried on my laptop (Windows 10 64bit, 6 Core) to extract a slpk file (3Gb) to eslpk to S3 bucket in a Windows command like below, in which I set multithreads count to 6.  But I don't see the executable is running multithreads. 
`i3s_converter.exe --extract my.slpk -d s3://mys3bucket -a mykey -s myskey -r ap-southeast-2 -t 6`

Thank you.

**Comment by rvargasESRI** [comment]
@JackFanZhang Hello Jack, we will look into this. Thank you for bringing it to our attention.

**Comment by rvargasESRI** [comment]
@JackFanZhang The multithreaded option is currently ignored for the extract command. 
The extract command is always multithreaded, with the number of threads being equal on the number of cores available. 
This will be updated in documentation. Thank you.
