### ISSUE TITLE
geometryDefinitions is still required 

### ISSUE THREAD

**Issue by disednet** [Esri/i3s-spec#137]
According to your documentation for version 1.8, I generate 3dSceneLayer.json without "geometryDefinition" because it is not marked as required. But when I check the final model with i3s_converter or ArcGIS they return an error that I should determine "geometryDefinition". Can you clarify this moment?

**Comment by rvargasESRI** [comment]
@disednet This is a typo in the documentation. `geometryDefinition` is still required in 1.8

I will update the doc to properly require this.
