### ISSUE TITLE
popupInfo isn't documented?

### ISSUE THREAD

**Issue by kelleyma49** [Esri/i3s-spec#14]
I don't see documentation for the type popupInfo. it's not  #listed in the class 3dSceneLayerInfo type (https://github.com/Esri/i3s-spec/blob/master/format/Indexed%203d%20Scene%20Layer%20Format%20Specification.md#class-3dscenelayerinfo).

**Comment by jgravois** [comment]
just a shot in the dark, but it is likely recycled from the Web map/Web scene [specification](https://developers.arcgis.com/web-scene-specification/objects/popupInfo/).

**Comment by kelleyma49** [comment]
Thanks. It might be nice to link to that in the specification.

**Comment by jfoster126** [comment]
popupInfo is documented here

https://github.com/Esri/i3s-spec/blob/59cfee45529e382694d44c192573e5774a921550/docs/1.6/popupInfo.cmn.md
