### ISSUE TITLE
strange error happened SLPK_FILE_METHOD_NOT_STORE

### ISSUE THREAD

**Issue by disednet** [Esri/i3s-spec#141]
I couldn't upload the slpk file and then checked it with i3_converter. It informed me that the file contented a wrong resource and the description was "Warning : Loading resource sublayers/0/nodes/root/3dNodeIndexDocument failed with error:SLPK_FILE_METHOD_NOT_STORE". Could you explain what it does mean?

**Comment by rvargasESRI** [comment]
@disednet Can you upload an example SLPK?

Every node requires a https://github.com/Esri/i3s-spec/blob/master/docs/1.8/3DNodeIndexDocument.cmn.md so either your missing the document per node or it is not valid.

**Comment by rvargasESRI** [comment]
@disednet I have a correct to my comment above.
The error message you are receiving is due to a portion of the archive being compressed where it should not be.
Please see
https://github.com/Esri/i3s-spec/blob/master/format/Indexed%203d%20Scene%20Layer%20Format%20Specification.md#scene-layer-packages-

**Comment by disednet** [comment]
@rvargasESRI I attached the model through [google drive](https://drive.google.com/file/d/133KWrEsMUx-yMgiCEEVGMPgkAvM3RFTz/view?usp=sharing). I double-checked that the file exists and zip is on the STORE state.

**Comment by disednet** [comment]
> @disednet I have a correct to my comment above. The error message you are receiving is due to a portion of the archive being compressed where it should not be. Please see https://github.com/Esri/i3s-spec/blob/master/format/Indexed%203d%20Scene%20Layer%20Format%20Specification.md#scene-layer-packages-

According to the document you attached, I could compress the scene with STORE MODE, but for every file inside SLPK structure, I can choose gzip compressor with the certain level of the compression.

**Comment by disednet** [comment]
I found the error, actually, it was a file with metainfo which was compressed with another level of compression.
