### ISSUE TITLE
LoD Selection

### ISSUE THREAD

**Issue by Shtirlic81** [Esri/i3s-spec#15]
Hi,

I am having trouble to understand the LOD selection. 

For example, if I have: 

  "lodSelection": [
    {
      "metricType": "maxScreenThreshold",
      "maxError": 539.29734222795435
    }
  ],

And mbs: 

  "mbs": [
    -43.193687596934836,
    -22.968234420300959,
    196.58792681110327,
    539.29734222795435
  ],

My graphics configuration is FOV of 3.0, aspect ratio of 1.0 and near plane at 1.0… window size is 800x800.

How do I calculate when to change the LOD?

**Comment by sreinhard** [comment]
The LoD computation works as follows

1. Project bounding sphere on screen plane and compute its radius in pixels. (see eg. here for an example of how to do this: https://stackoverflow.com/questions/21648630/radius-of-projected-sphere-in-screen-space)
2. Switch LoD to children if this radius is bigger than maxError.

**Comment by Shtirlic81** [comment]
Great, thanks.
I didn't understand it from the example comments.

**Comment by Shtirlic81** [comment]
Hi, I have another question regarding LoD selection.

In the spec there are two fields: metricType and maxError, but in the explanation it is written that "Cookers can add as many LodSelection objects as desired, but must provide one as soon as the layer's lodType is not null. Of the three min/avg/max values, typically only one or two are used."

So as I understand, the coockers can add avgScreenThreshold as metricType and than the second filed will be avgError? Or you meant something else?

Thanks
