### ISSUE TITLE
Issue with highlighting in BuildingSceneLayer

### ISSUE THREAD

**Issue by bloigge** [Esri/i3s-spec#153]
We currently face the problem that we can't see selected elements in a SceneViewer with our created SLPK / i3s and we are not aware of what is actually missing. When we click on a wall element for example we get the information in the pop-up, but the element is not highlighted (red area in the screenshot should be highlighted) and we get an error in the browser console. In ArcGIS Pro at least the slpk highlights the element shortly (flashing) but is also missing the "blue" selection mask.

![image](https://user-images.githubusercontent.com/7089726/204814283-1ac00afd-6ade-4b6c-b77d-fd1c6f063fc3.png)

Example file for download:
https://www.dropbox.com/s/h6m5qq5v4e04xjd/Sample.slpk?dl=0

**Comment by bloigge** [comment]
FYI - we are writing the SLPK on our own. No usage of ArcGIS Pro.

**Comment by sreinhard** [comment]
Hi @bloigge 

For the highlighting to work properly, you should have a field with type "esriFieldTypeOID" that defines the field name for the object ids stored in the geometry.

**Comment by bloigge** [comment]
Thank you! The esriFieldTypeOID was the missing part - works now! 

We have one additional question:
In the [docs ]( https://github.com/Esri/i3s-spec/blob/master/docs/1.8/sublayer.bld.md)it says that ```Semantics for work discipline groups which can be used to refine the user experience. Possible values are: Mechanical, Architectural, Piping, Electrical, Structural``` - are the disciplines really limited to those values or can we also define custom ones? Is it also only limited to two levels?

If this is not the right place to ask - please let me know if there are any other communication channels or if I should open a new issue.
