### ISSUE TITLE
The count of normal attribute not equal to vertex count in geometry file with draco compressed

### ISSUE THREAD

**Issue by alunAlunnnnn** [Esri/i3s-spec#159]
Hello,

I am tring to extract geometry data, such as `position`, `normal`, `uv` and `uvr` from the geometry file with draco compressed, the count of `uv` and `uvr` is correct with vertex count, but the count of `normal` attribute is less than the vertex count. So is it possible to match the `normal` with each vertex?

![image](https://github.com/Esri/i3s-spec/assets/49191632/cfa658c1-b1cd-4c37-910c-a80194d63c94)

I have tried several slpk files, it is a common problem.

And I have read the geometry file without draco compress, it is correctly right.

All of my slpk file were created by ArcGIS Pro ( v3.1, v2.8 or earier version).

The sample data is [here](https://1drv.ms/u/s!Aiucgj7czT2NgbMJihvqkROtvAElHA?e=iFQLXU)

Thanks, a lot.

**Comment by ajuanr** [comment]
@alunAlunnnnn Draco compression may deduplicate attribue values and vertices. I would suggest visiting the [Draco repo](https://github.com/google/draco) for information on reading the compressed buffer.

**Comment by alunAlunnnnn** [comment]
> @alunAlunnnnn Draco compression may deduplicate attribue values and vertices. I would suggest visiting the [Draco repo](https://github.com/google/draco) for information on reading the compressed buffer.

Thanks a lot for reply, so it means that, the application can not read the correct normal values from draco geometry file?

**Comment by ajuanr** [comment]
@alunAlunnnnn Applications can recover atributes as attributes contain a mapping between points indices and attributes indices and multiple points can be mapped to the same attribute values.
