### ISSUE TITLE
SLPK to i3s fails on enterprise

### ISSUE THREAD

**Issue by bloigge** [Esri/i3s-spec#161]
We have recently upgraded our (staging) Enterprise System to 11.1 (last week). We have been capable of working with our custom created SLPK files before the upgrade (uploading first the SLPK and then publishing as i3s service via REST API).

Unfortunately since the upgrade to 11.1 many of our self created SLPKs stopped working. Are there any Change-Logs regarding the GP Tools that extract SLPK during publishing?

[Here ](https://www.dropbox.com/s/4p26fqgm3hjmy2f/last_week_newly_uploaded.slpk?dl=0) is an example of a file that definitely worked before the upgrade and still works on our production system which we want to upgrade in the following weeks.

**Comment by ajuanr** [comment]
@bloigge 
File paths in an slpk must use a forward slash. A backslash is incorrect, per the [ZIP file format specification](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT).

**Comment by bloigge** [comment]
@ajuanr  Thank you, works now with forward slashes.
