### ISSUE TITLE
Questions about UV Mapping of Atlas Textures

### ISSUE THREAD

**Issue by CrashedBboy** [Esri/i3s-spec#17]
Hi, 

Recently I'm trying to display i3s buildings on Cesium.js,  
the normals and vertices parsed from geometry binary show the buildings' polygons really well.  
![building without texture](https://i.imgur.com/ziITuvR.png)  
then I parsed and got the uv0 for textures mapping,  
I parsed each feature's uv0 in the node, and used features' uv (array) to map the node's texture onto the geometric polygons, 
(each node has only one atlas image texture in the [i3s layers I tested](http://www.arcgis.com/home/item.html?id=d3344ba99c3f4efaa909ccfbcc052ed5) )
but it seems that the images mapped onto the polygon weren't matched.

My result:
![mapping result](https://i.imgur.com/7x4uirS.png)
Correct looking (screenshot of [ArcGIS web viewer](http://www.arcgis.com/home/webscene/viewer.html?layers=d3344ba99c3f4efaa909ccfbcc052ed5)):  
![correct result](https://i.imgur.com/zr9H1bW.png)  

I've checked some nodes textures, each node has only one aggregated texture image like this:  
![aggregated texture](https://i.imgur.com/rmWoGej.jpg)  

So, my questions are:  
1. Are the uv of each feature in node the **coordinates of the whole atlas texture**? or I need to seperate the atlas texture into several subImages because the uv is the **coordinate of subImages** instead of a whole atlas.
2. If the uv is the coordinate of subImage, how can I sperate the atlas into subImages? I saw there is an attribute named `subimageRegion` from [spec document](https://github.com/Esri/i3s-spec/blob/a22e94d8bcf484f106f0231baa01793a58959741/format/Indexed%203d%20Scene%20Layer%20Format%20Specification.md#atlas-usage-and-regions), but I don't know where the attribute is.

Thanks for reading such a long question.

ps. codes of how I parse the uv0: [github link](https://github.com/CrashedBboy/i3s-web-client/blob/2ac523b03fdc3338af3792fc76c7150e5c9195f6/static/js/index.js#L303)

**Comment by sreinhard** [comment]
1. The service you are referring to does not use subimage regions, so the uv coordinates are coordinates of the whole atlas texture.
2. For services that use vertex regions there is an additional vertex attribute with 4 16 bit values that identifies the sub image.

Did you try to flip the v-coordinate? (v = 1 - v) Depending how you define your texture coordinate system this is sometimes necessary.
