### ISSUE TITLE
Parameter Definition Issues

### ISSUE THREAD

**Issue by intckarl** [Esri/i3s-spec#20]
I found maxScreenThresholdSQ under lodSelection, with a similar parameter named maxScreenThreshold without SQ.

But in your doc, there is only description for maxScreenThreshold, so I'm wondering what does SQ means and how does it effect lodSelection

Thank you

**Comment by jfoster126** [comment]
Hi @intckarl , 

The maxScreenThresholdSQ values are calculated 
```
maxScreenThresholdSQ = PI * 0.25 * maxScreenThreshold * maxScreenThreshold
```

`maxScreenThresholdSQ` is used to help with better view frustum culling and increases benefits from the non-isotropic screen projected size.  

I will add this to the spec as well, thank you food your feedback.

**Comment by intckarl** [comment]
@jfoster126  Thank you for reply!  
One more thing, there are still some more unclear things in the I3S document.
Some have totally different name and where to use, but with the same description.
Also there are parameters just say "Definition missing!" (lodModel in store.cmn.md)
And there are parameters without any description at all...
Would you please fix these? I really want to get a real study in this.
Thank you.

**Comment by jfoster126** [comment]
@intckarl We are actively working on the spec and hope to release an updated version this summer.

**Comment by jfoster126** [comment]
Hi @intckarl , 

We pushed an [update to the spec](https://github.com/Esri/i3s-spec/pull/32) today that includes fixes for these issues. Please open a new issue if you find anything else or have more questions. Thanks.
