### ISSUE TITLE
Add Skyline PhotoMesh software to the “Where Can I Use...?” listing

### ISSUE THREAD

**Issue by yanivday** [Esri/i3s-spec#21]
Hello @Tamrat-B , 
My name is Yaniv Dayan from Skyline Software Systems. producer of PhotoMesh (http://www.skylineglobe.com/SkylineGlobe/corporate/Products/photomesh.aspx) software, that produces high-resolution, textured, 3D mesh models from standard 2D photographs. 
One of our supported output formats is I3S, and we wanted to see if it is possible to add our software to the “Where Can I Use...?” listing (https://github.com/Esri/i3s-spec#where-can-i-use):
Vendor: Skyline / Skyline Software Systems, Inc.
Product/URL: PhotoMesh (http://www.skylineglobe.com/SkylineGlobe/corporate/Products/photomesh.aspx)
Scene Layer Type: IntegratedMesh
Please let me know what is the best way to make this happen. 
(I also sent a comment on Update README.md)
Thanks for your help and the great format.

**Comment by jfoster126** [comment]
We have verified the data and added Skyline to the ReadMe.  https://github.com/Esri/i3s-spec/pull/26
