### ISSUE TITLE
Performance Issue on High Resolution Display

### ISSUE THREAD

**Issue by intckarl** [Esri/i3s-spec#22]
We have a slpk file directly generate by Context Capture from oblique photographic images.
We publish a service and view it online in SceneViewer.
It doesn't have any geometry at root(level 1) and level 2 nodes. Although we believe this would be a Context Capture problem, but also something we want to ask here.

On my own computer, with a 1080P display, it looks fine. 
But on other computer, with dual-4K display, it took very long time to load in full extent, and seems fine if only focus to very small, local extent.

We've tried to turn up the maxError value on level 3, I believe that would force to load only level 3 which is smaller and faster.
Still fine in my 1080P display, very little improve in dual-4K display.

So I start to wonder, how does it react on high resolution display? What's the difference between 1080P and dual-4K display? What can I do to improve this?

Thank you.

**Comment by intckarl** [comment]
We are working with ArcGIS Pro 2.3 and Enterprise 10.7
Both computer and the host server have hi-end environment so it's not on this

**Comment by jfoster126** [comment]
There might be a Scene Viewer/JavaScript API issue involved in addition to the uncompressed textures. 

Would you create a thread on GeoNet for this issue? That way we can get support to follow up and track it.  This repo tends to be for mainly Scene Layer specific issues, more of our SV/JSAPI users are on GeoNet.  I recommend this forum

https://community.esri.com/community/gis/3d
