### ISSUE TITLE
Extent should be 3D

### ISSUE THREAD

**Issue by abellgithub** [Esri/i3s-spec#25]
The extent as shown [here](https://github.com/Esri/i3s-spec/blob/master/docs/2.0/store.pcsl.md) is 2D.  This seems strange and limiting for a point cloud, which is naturally a 3D object.  Is this information available elsewhere?

**Comment by jfoster126** [comment]
Hi @abellgithub - The extent is 2D for legacy reasons and compatibility with other layer types. The root node should have the [Oriented Bounding Box](https://github.com/Esri/i3s-spec/blob/bc1ad34b81070fd0b108a12d8d1dbd83a1d771ed/docs/1.6/obb.cmn.md) information for the layer.

**Comment by jfoster126** [comment]
@abellgithub closing this issue, please reopen this thread if you still have questions on this topic. Thanks.
