### ISSUE TITLE
Question: Material Definition

### ISSUE THREAD

**Issue by Shtirlic81** [Esri/i3s-spec#30]
Hello,

I'm trying to understand more deeply the format. Right now I'm focusing on the material.

In materialDefinition there are three parameters that I don't understand:
- vertexRexion
- vertexColors
- useVertexColorAlpha

What do they mean and how should I use them?
Why they are defined as array (boolean[])?

Thanks
Three of them defined as boolean array (boolean[]). the question is why?

**Comment by sreinhard** [comment]
Hi @Shtirlic81 

vertexRegion: This flag indicates that the geometry has uv region vertex attributes. These are used for adressing subtextures in a texture atlas. The uv coordinate are relative to this subtexture in this case.

vertexColors: This flag indicates that the vertex color attribute of the geometry should be used to color the geometry for rendering.

useVertexColorAlpha: This flag indicates that the alpha component of the vertex color attribute should be used for transparently rendering the geometry.

> Why they are defined as array (boolean[])?

They should be defined as `boolean`. Thanks for bringing this up.

**Comment by Shtirlic81** [comment]
Thanks

**Comment by jfoster126** [comment]
@Shtirlic81 We updated the spec to include these details.  Thanks.

https://github.com/Esri/i3s-spec/blob/master/docs/1.7/params.cmn.md
