### ISSUE TITLE
LoD Selection structure

### ISSUE THREAD

**Issue by Shtirlic81** [Esri/i3s-spec#31]
Hi,

In the spec there are two fields: metricType and maxError, but in the explanation it is written that "Cookers can add as many LodSelection objects as desired, but must provide one as soon as the layer's lodType is not null. Of the three min/avg/max values, typically only one or two are used."

So as I understand, the cookers can add avgScreenThreshold as metricType and than the second filed will be avgError? Or you meant something else?

Thanks

**Comment by jfoster126** [comment]
Hi @Shtirlic81,

We recently updated the doc for LOD Selection with more details about `metricType` and `maxError`. https://github.com/Esri/i3s-spec/blob/master/docs/1.7/lodSelection.cmn.md

Please let us know if you need more information. Thanks.

**Comment by Shtirlic81** [comment]
Ok, thanks, it's mych more clearer.

I have only one question:
Normalizaed distance its the distance of the node from the camera, divided by the distance of the camera from the origin?

**Comment by jfoster126** [comment]
Hi @Shtirlic81, 

Our apologies, the `distanceRangeFromDefaultCamera` is **not** normalized.  It is the distance from the surface of the node's minimum bounding volume to the camera. We will update our documentation to reflect this. Thanks.

**Comment by jfoster126** [comment]
Updated [lod Selection metrics](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/lodSelection.cmn.md)
