### ISSUE TITLE
i3s_converter doesn't properly set exit code

### ISSUE THREAD

**Issue by kelleyma49** [Esri/i3s-spec#38]
The i3s_converter application doesn't set the exit code to a non-zero value if it fails. Ideally, the exit code should be non-zero if an error occurred and zero if no error occurred.

**Comment by jfoster126** [comment]
Hi @kelleyma49 , 

We released a new version of the converter with your requested update for exit code. Please let us know if the update is in line with what you need.

**Comment by kelleyma49** [comment]
Awesome, thank you! It seems to work!
