### ISSUE TITLE
i3s_converter doesn't output a json log if the file passed to the -u subcommand doesn't exist

### ISSUE THREAD

**Issue by kelleyma49** [Esri/i3s-spec#39]
The i3s_converter application doesn't output a json log if the file passed to the -u subcommand doesn't exist. It should output a json log with the results and it should also set the exit code (see #38).

**Comment by jfoster126** [comment]
Hi @kelleyma49 , 

We released a new version of the converter with your requested update for the log output. Please let us know if the update is in line with what you need.

**Comment by kelleyma49** [comment]
Awesome, thank you! It seems to work!
