### ISSUE TITLE
How to Convert v1.4 or v1.5 to V1.7 （just i3s ,not  slpk）

### ISSUE THREAD

**Issue by congying2** [Esri/i3s-spec#40]
1、slpk have Size limitation;
2、i3s(not slpk)  high Generality;
3、How to Convert v1.4、 v1.5、v1.6   to V1.7 （just i3s ,not  slpk）

**Comment by jfoster126** [comment]
Hi @congying2 , 

1. SLPK do not have any size limitation. 
2. Can you provide more details about this question? I'm not sure what you are askin. 
3. There is limited support with the converter for converting SLPK from 1.4 to 1.7 and 1.5 to 1.7.  The converter only converts SLPK at this time.
