### ISSUE TITLE
About maxScreenThreshold and screen size? 

### ISSUE THREAD

**Issue by intckarl** [Esri/i3s-spec#41]
How to define maxScreenThreshold? Is it pixel or dpi or something else?

What's the relation with diameter of the node's minimum bounding sphere?

**Comment by jfoster126** [comment]
Hi @intckarl , 

The details for `maxScreenThreshold` and its relation to the MBS are in the [lodSelection](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/lodSelection.cmn.md).  Here is the text:

_`maxScreenThreshold`: A per-node value for the maximum pixel size as measured in screen pixels. This value indicates the upper limit for the screen size of the diameter of the node's minimum bounding sphere (MBS). In other words, the content referenced by this node will qualify to be rendered only when the screen size is below the maximum screen threshold value. Used with the mesh pyramid profile._
