### ISSUE TITLE
I3S convert tool is failed

### ISSUE THREAD

**Issue by giserHacter** [Esri/i3s-spec#47]
hello!
there are some errors when i use the i3s_converter tool,the slpk is producted by arcgis pro and 
the error is "Failed to decode image nodes/19-1-0-0-0-2-0/textures/0_0 using method jpg".
Can you add an error skip command to you program,eg:try sth except pass.
![IMG_2446](https://user-images.githubusercontent.com/37400203/63010403-ec589900-beb8-11e9-882a-b8cfdc3f226e.JPG)

**Comment by jfoster126** [comment]
Hi @giserHacter ,

There are two possible cases: 
1. Texture file is corrupted/truncated/non-baseline JPG
2. File is declared as JPG in the “shared” JSON resource but is actually something else (PNG or DDS ?) 

Would you be willing to share this particular data with us? Thanks.
