### ISSUE TITLE
OBB

### ISSUE THREAD

**Issue by Shtirlic81** [Esri/i3s-spec#49]
Hi, I have a couple questions:
1. I'm not familiar with quaternion, how do I use it in order to get the correct orientation?
2. What are the units of quaternion's members? Is it degree, degree, degree, meter?

Thanks

**Comment by sreinhard** [comment]
Hi,

1. Quaternions are a common representation for 3d orientations. See https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation
There are various libraries that can handle quaternions for you, eg. glMatrix has functions to transform 3d vectors (http://glmatrix.net/docs/vec3.js.html#line514) and to convert them to other representations, such as transformation matrices (http://glmatrix.net/docs/mat3.js.html#line492).

2. The quaternion does not have units. It should always have norm 1, ie. the sum of the squares of the numbers in the quaternion is equal to 1.

**Comment by Shtirlic81** [comment]
Thanks
