### ISSUE TITLE
Add Sample SLPKs for 3D Object, IntegratedMesh, 3D Point

### ISSUE THREAD

**Issue by chri7928** [Esri/i3s-spec#5]
Add some sample SLPKs for currently available scene layer types.

**Comment by Ivonne-S** [comment]
We have added examples to each layer types:
[Building Scene Layer](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/BSL_ReadMe.md)
[Point Scene Layer](https://github.com/Esri/i3s-spec/blob/master/docs/1.6/Point_ReadMe.md)
[Point Cloud Scene Layer](https://github.com/Esri/i3s-spec/blob/master/docs/2.0/pcsl_ReadMe.md)
[3D Object Scene Layer](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/3Dobject_ReadMe.md)
[Integrated Mesh Scene Layer](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/IntegratedMesh_ReadMe.md)

**Comment by Tamrat-B** [comment]
@Ivonne-S thanks!
