### ISSUE TITLE
i3s to other 3D format.

### ISSUE THREAD

**Issue by Shimoorook** [Esri/i3s-spec#51]
Hope this finds you well.

I'm trying to use an i3s file to create a VR model in CityEngine.
My initial thought was that CityEngine would be able to take i3s or slpk, but it turns out that it doesn't. Do you have any recommendations on how to convert or work around the current limitation?

**Comment by SGoetschi** [comment]
Hi @Shimoorook 

Do you get your data as SLPK or do you create the SLPK yourself?
Maybe you can get a different format into CityEngine.

SLPK is designed for streaming/viewing - not for further processing.

**Comment by Ivonne-S** [comment]
Hi @Shimoorook 

We currently don't have the support you are looking for but this is a limitation we would like to overcome in the future. what @SGoetschi is referring to is the current status. Would it be possible for you to give us further information on the workflow you have in mind?
