### ISSUE TITLE
i3s 1.7 geometry file

### ISSUE THREAD

**Issue by giserHacter** [Esri/i3s-spec#52]
hello,I find 1.bin.gz file in geometries floder in i3s 1.7 and Is it comes from Draco compression?

**Comment by Ivonne-S** [comment]
Yes, the file the file 1.bin.gz in i3s 1.7 is a Draco compressed file. 
The following attributes may be compressed: position, normal, uv0, color, uvRegion, and feature-index
-	Normals are only compressed if smooth normals exist.
-	Colors are only compressed if they are not all opaque white.
You can find which attributes have been compressed in the 3DSceneLayer.json file, under the geometryDefinitions.geometryBuffers property.
