### ISSUE TITLE
SharedResource encoding

### ISSUE THREAD

**Issue by Shtirlic81** [Esri/i3s-spec#53]
Hi,

In store module, shared resource encoding is missing (like for nidEncoding, or feature encoding...)

**Comment by ajuanr** [comment]
Shared resource encoding is not part of the I3S-spec as it is not being written to an slpk.

[Shared resources](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/sharedResource.cmn.md) contain material and texture definitions and are stored as JSON files.

As of version 1.7, shared resources have been deprecated and are no longer being used. They are included for backwards compatibility.
