### ISSUE TITLE
Features Attributes

### ISSUE THREAD

**Issue by Shtirlic81** [Esri/i3s-spec#54]
Hi,

In features file there is a definition of the geometry structure:

vertex ==> offset, number of elements...
normal ==> offset, number of elements...

I don't see the same definition for the features, such as Id and face range, where can I find their offset information?

Thanks

**Comment by ajuanr** [comment]
If the offset information is not available in the features file, you can examine uncompressed geometry buffer.

The buffer contains an 8-byte header. The first 4 bytes is the vertex count and the next 4 is the feature count. The bytes are in little endian order.

The order of vertex attributes is fixed:
`position`  
`normal`  
`uv0`  
`uv1`  
`color`  
`uvRegion`  
`featureId`  
`faceRange`

All vertex attributes have a fixed size that can be computed as:
`#component * sizeof( type ) * {#vertices or #features}`

**Comment by Shtirlic81** [comment]
Why not put this information, and let the user calculate and extrapolate this base on the geometry size?

**Comment by rvargasESRI** [comment]
@Shtirlic81 Could you clarify a bit more about how this relates to the original issue posted?  Thank you.
