### ISSUE TITLE
Error converting to SLPK 1.7 from 1.5

### ISSUE THREAD

**Issue by crazymaps1980** [Esri/i3s-spec#55]
Hi, 

Currently trying to convert a 1.5 slpk file to 1.7 and the following message occurs

{
"version" : "0.5.07162019",
"log" : [{
"code" : "7009",
"level" : "Error",
"message" : " JSON parsing error in \"nodes/0-2-1-2-1-3-1-1-0-3-3/features/0\":  * Line 1, Column 1\n  Syntax error: value, object or array expected.\n"
}
],
"success" : false
}

We know that we have some empty nodes, but is there any way to skip this issue, as the conversion fails.

Thanks

**Comment by ajuanr** [comment]
Based on the error, it looks like there is a problem with the JSON file in:
 `nodes/0-2-1-2-1-3-1-1-0-3-3/features`

Most likely, this file is empty, which is causing the error.

Would you be able to confirm if this is the case?
