### ISSUE TITLE
3D object geometry format undocumented?

### ISSUE THREAD

**Issue by barf** [Esri/i3s-spec#57]
I am unable to find the specification for the binary geometry format indicated in 3D object and mesh SceneLayers. 

Can someone point to me where I can find documentation on this file format?

In practice the content-type is application/octet-stream and it is delivered as a .bin - I'm guessing it's a TLV format reminiscent of ASN.1 but unable to find any official information about this ".bin" format.

This is the data I'm trying to work with:
```
$ hexdump -C 0.bin |head
00000000  1b 0f 00 00 1f 00 00 00  05 36 02 ba 9b 12 ab b8  |.........6......|
00000010  d5 5e 5c 41 60 4c 05 ba  1d b9 b0 b8 d5 5e 5c 41  |.^\A`L.......^\A|
00000020  f2 8b 01 ba 73 b2 b7 b8  d5 5e 5c 41 86 b4 08 ba  |....s....^\A....|
00000030  fa 5f b1 b8 3e 5f 5c 41  c4 17 0a ba 4f 84 9c b8  |._..>_\A....O...|
00000040  3e 5f 5c 41 4f 1f 0b ba  ba 24 b8 b8 d5 5e 5c 41  |>_\AO....$...^\A|
00000050  ce df ff b9 05 9e 97 b8  3e 5f 5c 41 60 4c 05 ba  |........>_\A`L..|
00000060  1d b9 b0 b8 d5 5e 5c 41  05 36 02 ba 9b 12 ab b8  |.....^\A.6......|
00000070  d5 5e 5c 41 83 98 0b ba  a6 78 55 b8 3e 5f 5c 41  |.^\A.....xU.>_\A|
00000080  ce df ff b9 05 9e 97 b8  3e 5f 5c 41 4d 87 f5 b9  |........>_\AM...|
00000090  9e 25 75 b8 3e 5f 5c 41  b6 94 f2 b9 dd 98 64 b8  |.%u.>_\A......d.|
```

**Comment by ajuanr** [comment]
The `.bin` file is not a new format, but simply a binary file.

The first 8 bytes of this file are the header. The byte order is little endian.
The first 4 bytes (0x00000F1B = 3867) is the number of vertices.
The next 4 bytes (0x0000001F = 31) is the number of features.

More information on the geometry buffer can be found here:
https://github.com/Esri/i3s-spec/blob/master/docs/1.7/geometryBuffer.cmn.md
