### ISSUE TITLE
How to adjust 1.7's texture

### ISSUE THREAD

**Issue by intckarl** [Esri/i3s-spec#58]
There used to be shared resourse in each node to contorl material and texture, but in 1.7, the shared resourse is deprecated, now there is only one materialDefinitions in 3DSceneLayer.json.

So how does it control texture in every node?

**Comment by ajuanr** [comment]
In 3DSceneLayer.json, the `materialDefinitions` property is an array of `materialDefinitions`, which may contain multiple `materialDefinitions`

The [nodepage](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/nodes.cmn.md) may contain a `mesh.material.definition` with the index to the corresponding `materialDefinition` in the `materialDefinitions` array, for each node.

Within each `materialDefinition` some properties may contain a `textureSetDefinitionId` with the index of the texture in [textureSetDefinitions](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/textureSetDefinition.cmn.md).
