### ISSUE TITLE
How to set pbr material ?

### ISSUE THREAD

**Issue by intckarl** [Esri/i3s-spec#59]
Like the last issue, there is only one materialDefinitions in a slpk file.

In glTF there is name of every material, but I didn't see that in materialDefinitions.cmn.md, I really can't see how to control each and every node's material and texture.

**Comment by ajuanr** [comment]
The materialDefinitions in 3DSceneLayer.json can have more than one materialDefinition object. By adjusting the [material](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/meshMaterial.cmn.md) property within the [nodepage](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/node.cmn.md), you can control the material and texture for every node.
