### ISSUE TITLE
Can you give me some code template about compresion geometry by draco?

### ISSUE THREAD

**Issue by giserHacter** [Esri/i3s-spec#60]
Hello,Intckarl:
I use draco_decoder.exe and draco_encoder.exe to compress/uncompress geometry(include:position,normal,uv,color...) into 1.bin.gz file. This approach uses an intermediate file
(eg:obj file) and i did't like this way.So,can you give me a sample code that compress/uncompress the
geometry into draco.thank you very much!

**Comment by ajuanr** [comment]
We are working on an update for the doc to include a small sample. We are also working on an I3S SDK that should help with draco compression used in i3s. I don't have an exact release schedule. My apology for not providing this to you any sooner.

**Comment by rvargasESRI** [comment]
@giserHacter 
Example of writing SLPKs can be found here https://github.com/Esri/i3s-lib/ which includes Draco compression.
