### ISSUE TITLE
What rules are used to divide the size of the geometric data in each node?

### ISSUE THREAD

**Issue by KeepFaithMe** [Esri/i3s-spec#63]
I konw the organization form of the i3s is quadtree or octree,so I want to konw What rules are used to divide the size of the geometric data in each node?could you pelease give me some advice! thank you !

**Comment by SG-Soon** [comment]
I have the same question. There are too many nodes in the scene layer package I generate by ArcGIS Pro 2.4, I want to generate a slpk file in which each node contains more geometric data.

**Comment by rvargasESRI** [comment]
Thank you for reaching out!
I3S is agnostic to the data partitioning scheme used (k-d trees, sparse octrees, quadtrees etc..).

I hope this helps.
