### ISSUE TITLE
Draco compression

### ISSUE THREAD

**Issue by giserHacter** [Esri/i3s-spec#65]
Hello,devs

I find draco compression in version1.7 document ,but ,i check the 1.bin.gz file and find it is diffent from google official document.The i3s spec document  is too cryptic for me, so could you give me
a sample code for it that describe how to compress i3s geometrybuffer into draco file.thank you 
very much!

**Comment by Ivonne-S** [comment]
Hello,

We are working on an update for the doc to include a small sample. We are also working on an I3S SDK that should help with draco compression used in i3s. I don't have an exact release schedule. (I think end of march) My apology for not providing this to you any sooner.

I will try to get the doc sample in sooner.

**Comment by rvargasESRI** [comment]
@giserHacter
Example of writing SLPKs can be found here https://github.com/Esri/i3s-lib/ which includes Draco compression.
