### ISSUE TITLE
what is featureidMappedFromFS

### ISSUE THREAD

**Issue by intckarl** [Esri/i3s-spec#67]
I found that in 3dSceneLayer.json of a building slpk generated by ArcGIS Pro, but not a word in the spec.

![image](https://user-images.githubusercontent.com/14276240/71428391-7af8e480-26fb-11ea-83b6-b43d6d87f606.png)

**Comment by Ivonne-S** [comment]
This is not part of the i3s spec. What version of ArcGIS Pro did you use? I would like to try if I can reproduce this.
There is a mapping of scene layer to feature service for scene layer with associated feature layer we are working on but this would be part of 1.8.

**Comment by rvargasESRI** [comment]
This appears to be a bug.  We will be sure to remove this.  Thank you.
