### ISSUE TITLE
Possible typo in i3s-spec/docs/1.7/BSL_ReadMe.md

### ISSUE THREAD

**Issue by intckarl** [Esri/i3s-spec#68]
Is 3dNodeIndexDocument.json also only for compatability? Not necessary?

![image](https://user-images.githubusercontent.com/14276240/71607482-dec85500-2bb4-11ea-863f-61b432b9786f.png)

Also, in i3s-spec/i3s_converter, could you change the X icon to √? It's really confusing right now.
![image](https://user-images.githubusercontent.com/14276240/71607548-3d8dce80-2bb5-11ea-99ec-b72ac150f1dc.png)

**Comment by intckarl** [comment]
Also same typo in 3d object and integrated mesh readme

**Comment by intckarl** [comment]
Or do you mean in PURE 1.7, 3dNodeIndexDocument is replaced by Hash table?

**Comment by intckarl** [comment]
Or do you mean in PURE 1.7, 3dNodeIndexDocument is replaced by Hash table and node page ?

**Comment by ajuanr** [comment]
Yes, for I3S version 1.7 the 3dNodeIndexDocument is included for backwards compatibility.

We will also update the symbol in the converter documentation to something less confusing. Thanks.
