### ISSUE TITLE
options for planetary

### ISSUE THREAD

**Issue by thareUSGS** [Esri/i3s-spec#7]
More of a question than an issue.

In looking over the spec I see statements like
- The location of all index-related data structures such as node bounding spheres **SHALL** be specified using a single, global geographic WGS 84 CRS.
and
- **Allowed** CRS specified using an EPSG code include: EPSG:4326.

but within the examples given, WGS 84 doesn't seem hard-wired and a specified WKT (or WKT v2) can be defined. Does this mean that other bodies like Mars can be defined? 

If there are too many assumptions within the spec to allow for off-Earth bodies, what happens when the geospatial community needs to transition away from WGS84 (to the next best ellipsoid)?

**Comment by jgravois** [comment]
> More of a question than an issue.

yes, but a good one! (and apparently something you've considered [before](https://github.com/Esri/raster-functions/pull/39)). i'll see what i can find out.

**Comment by jgravois** [comment]
i got some information from the team and it appears their intention is definitely to allow for different ellipsoids. we'll be thinking about how to clarify this during our next round of updates to the spec.
