### ISSUE TITLE
i3s_converter.exe not support unit of chinese

### ISSUE THREAD

**Issue by dansdocker** [Esri/i3s-spec#70]
i3s_converter.exe not support unit of chinese
{
"version" : "0.5.11192019",
"log" : [{
"code" : "7009",
"level" : "Error",
"message" : " JSON parsing error in \"/3dSceneLayer\":  JSON string \"heightModelInfo.heightUnit\" is not a known value for this enumeration (米)"
}
],
"success" : false
}

**Comment by Ivonne-S** [comment]
heightModelInfo is not localized. Only a set of units are supported https://github.com/Esri/i3s-spec/blob/master/docs/1.7/heightModelInfo.cmn.md
If you are writing i3s you would have to heightUnit as one that is supported.
