### ISSUE TITLE
Edit Feature Attributes In ArcScene

### ISSUE THREAD

**Issue by ZJAFFE** [Esri/i3s-spec#71]
With the workflows I perform in house as well as for clientele, I think it would be extremely valuable to be able to edit attribute data in ArcScene, whether the data is a BIM model of a 3D feature.

**Comment by Ivonne-S** [comment]
Do you mean supporting i3s in ArcGIS Desktop ArcScene or editing of attributes in general?
I agree that and API call that allows you to search for features and its attributes to select and eventually edit them would be very useful. We are working on an i3s SDK and this would be functionality we would like to include.

**Comment by ZJAFFE** [comment]
In AcrGIS Pro, I can edit the attributes, but once I publish that layer to ArcGIS Online and create a web scene, the attribute data cannot be edited, unlike a standard 2D web map.

**Comment by chri7928** [comment]
This is more a question for an Esri product channel on GeoNet than for the I3S Spec repo. However, it is possible to share a scene layer with an associated feature layer and then edit it in Pro and in custom web workflows.  We have not yet implemented attribute editing in the Scene Viewer.

https://pro.arcgis.com/en/pro-app/help/mapping/layer-properties/edit-a-scene-layer-with-associated-feature-layer.htm

Note that this is an Esri product implementation pattern and someone could implement a different pattern using the I3S spec in a non-Esri app.
