### ISSUE TITLE
layers and sub-layers in 1.7

### ISSUE THREAD

**Issue by Shtirlic81** [Esri/i3s-spec#76]
Hi,

I have a question regarding the layers and sub-layers structure:

1. Why layers and sub-layers structure supports only buildings, and sub-layers only group, 3D objects and points?
2. How can I divide into layers integrated-meshs and overlayers on-top of it, e.g. terrain, vegetation, roads...
3. Why layer and sceneLayer has the same file name 3DSceneLayer? It's confusing.

Thanks

**Comment by rvargasESRI** [comment]
Hello thanks for reaching out,

1. The building layer is the container for the group layers which represent the disciplines.  3D object layers encompass the category layers.

2. This is not possible to separate out in an integrated-mesh.  This is possible in ESRI ArcGIS Pro using a feature layer with an integrated mesh layer.

Thank you.
