### ISSUE TITLE
How to link 3d object scene layer to building scene layer ?

### ISSUE THREAD

**Issue by intckarl** [Esri/i3s-spec#77]
In docs/1.7/layer.bld.md
![image](https://user-images.githubusercontent.com/14276240/75367730-bda58b80-58fb-11ea-85a7-7875aa3ad031.png)

I'm not quite understand how to do that, could you please be more specific or add an example?

Thank you.

**Comment by rvargasESRI** [comment]
This is an HREF as an attribute which could be created by ArcGIS Pro, however not programmatically.
The documentation will be updated to reflect this accordingly.
