### ISSUE TITLE
Typo in docs/1.7/store.cmn.md

### ISSUE THREAD

**Issue by intckarl** [Esri/i3s-spec#78]
![image](https://user-images.githubusercontent.com/14276240/75416748-275c7e80-596a-11ea-8891-4a6cff1224f8.png)

**Comment by intckarl** [comment]
![image](https://user-images.githubusercontent.com/14276240/75417701-a783e380-596c-11ea-99db-07dcbdaf0e99.png)


And the same in store.psl.md

**Comment by rvargasESRI** [comment]
Thank you for reaching out.

These typos will be resolved in the next specification release
