### ISSUE TITLE
An enhancement request for improving the efficiency of the i3s_converter tool

### ISSUE THREAD

**Issue by zssai** [Esri/i3s-spec#80]
According to my testing, the i3s_converter.exe tool only occupy a cpu core to do the conversion job, and It takes about 1.5 hours for the conversion of a slpk file about 8G. However, the slpk files in our projects  are often tens or hundreds of GB, and then it will take a very very time if we want to do the conversion. 
Could you please improve the performance of the tool？For example, using more than one cpu core for the conversion.

**Comment by rvargasESRI** [comment]
Hello @zssai .  Thank you for your suggestion.  In the next spec update, we plan to release multi-threaded i3s_converter.  Hope this will suite your needs.

Best,
Richard

**Comment by zssai** [comment]
Thank you for your quick response.
To supplement this, it takes 16 hours for the conversion of a slpk of 51 GB.
