### ISSUE TITLE
After using the upgrade tool, the original transparent Settings are gone

### ISSUE THREAD

**Issue by HaiyangHsu** [Esri/i3s-spec#81]
slpk version 1.6:
![image](https://user-images.githubusercontent.com/9838706/77718009-c5507100-701c-11ea-8f03-63834dfe8e73.png)
after update:
![image](https://user-images.githubusercontent.com/9838706/77718302-8111a080-701d-11ea-94f0-1ffa22b9df69.png)

**Comment by rvargasESRI** [comment]
Thank you for bringing this to our attention.
Would you be able to provide us with a sample of your data (the 1.6 SLPK with a few objects to display this property)?

**Comment by rvargasESRI** [comment]
@HaiyangHsu 
We believe this to be an issue with the reordering of faces during the draco compression.  We are still looking into a fix for this, however this is dependent on draco capabilities.

**Comment by rvargasESRI** [comment]
@HaiyangHsu Can you please try to reconvert your SLPK as this should be fixed in the latest i3s_converter.exe

Thank you.
