### ISSUE TITLE
Enhancement request for adding an option for whether delete the geometry files of the old version

### ISSUE THREAD

**Issue by zssai** [Esri/i3s-spec#82]
After the conversion, I noticed, the new slpk becomes very large, and every node has two geometry files for it, including 0.bin.gz and 1.bin.gz. If one is for the old version, and the other is for the v1.7, can you provide an option that helped the user to determine whether delete the old version files when the conversion finished? The larger the slpk file is,after all, the longer it takes when publishing the slpk file.

**Comment by rvargasESRI** [comment]
Thank you for reaching out.  What clients will be consuming your data after the deletion of old geometries? (i.e. Pro 2.5? Pro 2.6?).

**Comment by zssai** [comment]
ArcGIS Pro 2.5 and later releases
ArcGIS Enterprise 10.8 and later releases
ArcGIS JavaScript API 4.14 and later releases

**Comment by rvargasESRI** [comment]
Thanks for your feedback, we've come to the decision that this could lead to unintended consequences.
In the future we would move to a major version (e.g. 2.0), and at that point we would remove uncompressed geometries.
