### ISSUE TITLE
Layer Format Specification: Wrong example for tree structure

### ISSUE THREAD

**Issue by romanCattaneo** [Esri/i3s-spec#83]
In the [hierarchy example](https://github.com/Esri/i3s-spec/blob/master/format/Indexed%203d%20Scene%20Layer%20Format%20Specification.md#tree-structure-) the tree node representation (image) is inconsistent with the schematic view. There is no node `K2` under `D2`, and `C1` should only be the parent of `F2` and `H2`. `I2` should be a child of `D2`.

![image](https://user-images.githubusercontent.com/63106648/79336686-7499ad00-7f24-11ea-84af-2284221032bf.png)

**Comment by romanCattaneo** [comment]
Note, the same tree is also used to explain [node pages](https://github.com/Esri/i3s-spec/blob/master/format/Indexed%203d%20Scene%20Layer%20Format%20Specification.md#node-page-) later in the documentation.

**Comment by rvargasESRI** [comment]
Hi @romanCattaneo ,

thank you for bringing this to our attention.  We will be sure to change the tree to correctly reflect the image.
