### ISSUE TITLE
For slpk in wgs84, the texture will be blurry after the conversion

### ISSUE THREAD

**Issue by zssai** [Esri/i3s-spec#85]
Hi, according to our testings, the texture of the slpk in wgs84 will be blurry after the conversion.
My colleague on our development team said, it seems to be the errors related to the geometry.
If you need the testing data, please be free to email me.

https://drive.google.com/open?id=1VMUknz34Cqe1qgb2vm4WkWZx4yvTAaIz
https://drive.google.com/open?id=1Bam-0XVHuk_1DTKRwqzYIvFx2oNqAtXA

**Comment by rvargasESRI** [comment]
Hi, thank you for reaching out.  

Are you converting from OSGB to I3S or I3S 1.6 to I3S 1.7?
We would also like test data (before conversion) to reproduce the issue.  Thank you.

**Comment by zssai** [comment]
Hi,
Please download the slpk from the google driver:
https://drive.google.com/open?id=1oIEqD5ymcFouPSWGnbLks-ZWRW4YXORy 
https://drive.google.com/open?id=1jW0wGthz04LM7dzdqk6KYI9NCRjFB7Mg 

Best Regards
Sai

 
From: rvargasESRI
Date: 2020-04-25 01:07
To: Esri/i3s-spec
CC: zssai; Author
Subject: Re: [Esri/i3s-spec] For slpk in wgs84, the texture will be blurry after the conversion (#85)
Hi, thank you for reaching out.
Are you converting from OSGB to I3S or I3S 1.6 to I3S 1.7?
We would also like test data (before conversion) to reproduce the issue. Thank you.

**Comment by rvargasESRI** [comment]
Hello @zssai ,

Please download our latest i3s_converter.exe and you should see your issue is resolved.

**Comment by zssai** [comment]
@rvargasESRI  Will you provide the linux version of the tool?

**Comment by rvargasESRI** [comment]
@zssai There are plans to port to linux, however we do not yet have a timeline for that.

**Comment by zssai** [comment]
Thank you for your response.
