### ISSUE TITLE
OBB description confusing

### ISSUE THREAD

**Issue by abellgithub** [Esri/i3s-spec#87]
https://github.com/Esri/i3s-spec/blob/master/docs/1.7/obb.cmn.md

In the above, the `halfSize` talks about the units of the `center`, rather than the `halfSize`.  It also seems at odds with the example at the bottom.

The example says that it's WGS84 (by which I assume you mean latitude/longitude/height in meters based on your description of `center`), but there is no -105 latitude.  If I take it to be longitude/latitude/height, it makes sense, but then `halfSize` makes no sense, because surely the X and Y aren't in degrees. 

Then you say something about the quaternion being ECEF, which seems strange, as that's a different system from the original one.  Is one expected to transform the center/halfSize to ECEF and then apply the quat?

Some examples with math would be very helpful.

**Comment by rvargasESRI** [comment]
Hello @abellgithub 
We have made changes to the OBB documentation.  Thanks for bringing this to our attention.
