### ISSUE TITLE
Any way to convert 1.5 spec to 1.6?

### ISSUE THREAD

**Issue by digiiitalmb** [Esri/i3s-spec#88]
Hi there,

I'm generating i3s with Bentley Context Capture, but that is using 1.5 spec. Any instructions on how to convert 1.5 to 1.6?

Thanks

**Comment by rvargasESRI** [comment]
Hello @digiiitalmb , thanks for the comment.

We only support conversion to 1.7 with our conversion tool.

Thank you.

**Comment by digiiitalmb** [comment]
Would it convert 1.5 to 1.7 though? or just 1.6 to 1.7?

**Comment by rvargasESRI** [comment]
@digiiitalmb Yes it will convert from 1.5 to 1.7
