### ISSUE TITLE
metadata.json docs gone? 

### ISSUE THREAD

**Issue by ladislavhorky** [Esri/i3s-spec#90]
Hello,

we [have come across a version of i3s/SLPK (1.7?) where supposedly `nodeCount` in metadata.json is no longer required](https://github.com/melowntech/workshop/issues/27). Searching the i3s specs, the contents of metadata.json do not seem to be documented anywhere now, though they were a few [versions before](https://github.com/Esri/i3s-spec/blob/ce6ab0f8cbe4980835d1bedeb83839b98a7dc178/format/Indexed%203d%20Scene%20Layer%20Format%20Specification.md#metadata).

Please advise where to find up-to-date docs for metadata.json.

Thanks, Ladislav

**Comment by chri7928** [comment]
Thank you for letting us know. We'll look into this ASAP.

**Comment by ladislavhorky** [comment]
Hi there, any progress on this? I still cannot find any mention of `metadata.json`, nor its contents.

**Comment by rvargasESRI** [comment]
Thanks for reaching out @ladislavhorky 

We will add this information to the i3s repo.  

Out of curiosity, what is it that you're using this for?

**Comment by ladislavhorky** [comment]
Hi, 

oh, I did not reference it before, my bad. We need it in [VTS Geospatial](https://vts-geospatial.org/) `slpk2vts` encoder https://github.com/melowntech/workshop/issues/27 . 

VTS Geospatial is a FOSS geospatial content streaming platform we maintain. We try to keep it interoperable with industry standard formats for 3D textured mesh - among other supported formats. The SLPK development seem to quite fast, so it's hard to keep up with the updates sometimes :)

**Comment by Tekn1ck** [comment]
To add to this we are using Skyline Photomesh software to export to i3s/slpk and then trying to convert to vts format but we are having nodecount errors. Skyline say they do not need nodecount to export to ARCGIS so do not include it in the metadata.json file - Ladislav and I are talking about this issue on the VTS workshop
