### ISSUE TITLE
Enhancement request for the extract command

### ISSUE THREAD

**Issue by zssai** [Esri/i3s-spec#94]
The extract command only supports three cloud storage, Microsoft Azure Blob, Amazon Web Services S3 and Alibaba OSS. 
However, if I use a S3 compatibility cloud storage —— the xsky cloud storage, the  QingCloud cloud storage, for example, how to extract the slpk to it?
Maybe there should be an option for the endpointURL.

**Comment by rvargasESRI** [comment]
Thanks for bringing this to our attention.  We will look into being able to specify a custom endpointURL for S3 compatible cloud storage.

**Comment by zssai** [comment]
Thank you for your response. Looking forwad to the update.

**Comment by rvargasESRI** [comment]
@zssai 
This functionality is now be available in the converter.

**Comment by zssai** [comment]
@rvargasESRI  Sorry for my late response, could you please give an example of that?

**Comment by rvargasESRI** [comment]
@zssai 
The command would just add the ```--endpoint-url``` option at the end.

Using an example from [here](https://github.com/Esri/i3s-spec/blob/master/i3s_converter/i3s_converter_examples.md#convert-to-cloud-format-i3srest),
```i3s_converter.exe -u myFile.slpk -d s3://mySlpkBucket -a AKIAIOSFODNN7EXAMPLE -s wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY -r us-east-1a --endpoint-url 127.0.0.1```

The new option flag can be found [here](https://github.com/Esri/i3s-spec/blob/master/i3s_converter/i3s_converter_ReadMe.md#options-
)
